title="My title"
description="my example template"

[options]
myVar = { FreeText = { prompt = "What value do you want your var to be?" }}
myBool = { Boolean = { prompt = "True or false?" }}
MyInt = { Integer = { prompt = "What number?"}}
MyFloat = { Float = { prompt = "What floating number?"}}
MyRegex = { Regex = { prompt = "Testing prompt", pattern = "test"}}
MyChoice = { Choice = { prompt = "Test choice", options = ["a", "b", "c"]}}
